name: lanyard_listening_along
description: "Listening along on Spotify using Lanyard API"
publish_to: "none"

version: 1.1.0

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_secure_storage: ^9.0.0
  landart: ^1.4.0
  http: ^1.1.2
  url_launcher: ^6.2.2
  window_manager: ^0.3.7
  system_tray: ^2.0.3
  webview_windows: ^0.3.0
  flutter_inappwebview: ^5.8.0
  path_provider: ^2.1.1
  wakelock:
    git:
      url: https://github.com/NightFeather0615/wakelock.git
      ref: main
      path: wakelock
  package_info_plus: ^5.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon.ico
    - assets/app_icon.png
